name: Ansible Workflow Test 

on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: [self-hosted, ak_instace_label]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Print a Test Message
        run: echo "GitHub Actions workflow is running successfully!"

      - name: Update package list and install ansible
        run: |
          sudo yum upgrade -y
          sudo yum install -y ansible

      - name: Verify Installaiton
        run: ansible --version

      - name: Run Ansible Playbook
        run: ansible-playbook -i localhost, playbook.yml
